# Generated by Django 3.1 on 2020-08-26 12:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=120, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_username', message='Username Must be Alphanumberic', regex='^[A-Za-z0-9]*$')])),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('major', models.CharField(default='None', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('account_type', models.CharField(choices=[('A', 'Assets'), ('L', 'Libility'), ('Rev', 'revenue'), ('EXP', 'Expense'), ('CAP', 'Capital'), ('AR', 'Accounts Receivable')], default='A', max_length=3)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AssetsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='asset name', max_length=65)),
                ('asset_type', models.CharField(choices=[], default='ASSETS', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='fiscal year', max_length=16)),
                ('DateFrom', models.DateField()),
                ('DateTo', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('journal_type', models.CharField(choices=[('Sale.', 'SALE'), ('Purchase.', 'PURCHASE'), ('Bank.', 'BANK'), ('Cash.', 'CASH'), ('General.', 'GENERAL')], default='Sale.', max_length=9)),
                ('defualt_credit_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_account_id', to='core.accountmodel')),
                ('defualt_debit_account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debit_account_id', to='core.accountmodel')),
            ],
        ),
        migrations.CreateModel(
            name='LibilitiesMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Libility name', max_length=65)),
                ('Libility_type', models.CharField(choices=[], default='libility', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('journal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_id_transaction', to='core.journalmodel')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('user_type', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fiscalyeal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fiscalyear_id', to='core.fiscalyear')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, null=True)),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_id_invoice', to='core.accountmodel')),
                ('journal_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Journal_id_invoice', to='core.journalmodel')),
            ],
        ),
    ]
